### ISSUE TITLE
Slack domain for discussion?

### ISSUE THREAD

**Issue by tcfuji** [Rory-Finnegan/Learn.jl#1]
I've been following the roadmap (https://github.com/JuliaStats/Roadmap.jl/issues/11) and wish to contribute too. Let me know if you'd be interested in a Slack domain for this repository or if the issues board is enough.

**Comment by rofinn** [comment]
Yeah, I think some kind of chat system like slack would be great for this repo, since there is still a lot of brainstorming that needs to happen. Although, it would be nice if there already was a julialang slack domain and we could just make a channel for this repo.

**Comment by svaksha** [comment]
...and then there is gitter: https://en.wikipedia.org/wiki/Gitter
Personally speaking, I'd prefer an unlogged irc channel on freenode, just like #julia

**Comment by rofinn** [comment]
Gitter seemed like the best option. Added the link to the README. While I do like the simplicity and anonymity of irc, it feels rather dated now.

**Comment by tcfuji** [comment]
Closing since Gitter seems good enough.
